### ISSUE TITLE
Documentation index files with all bad links

### ISSUE THREAD

**Issue by paulmasson** [sagemath/documentation#6]
In the webmaster tools for doc.sagemath.org Google reports some 30,000 bad links. I thought at first this was just bad data in the Google index and cleared out all of the indicated files, but more bad links began appearing soon after. The current entries all come from three index files:

http://doc.sagemath.org/html/en/a_tour_of_sage/py-modindex.html
http://doc.sagemath.org/html/en/developer/py-modindex.html
http://doc.sagemath.org/html/en/thematic_tutorials/py-modindex.html
http://doc.sagemath.org/html/en/prep/py-modindex.html

Every link I clicked on in these three files is bad. Presumably these files are autogenerated and there is something incorrect in the generation. I will add other index files to this list as Google identifies them.

**Comment by haraldschilly** [comment]
All files are generated by "Sphinx" and I don't really have an idea what does happen in detail. Maybe we should block all modindex.html files?

However, checking upon the first link in the first list, it seems like as if sphinx doesn't "cross link" to a sibling. I.e. instead of `/html/en/a_tour_of_sage/`

http://doc.sagemath.org/html/en/a_tour_of_sage/algebras/sage/algebras/affine_nil_temperley_lieb.html#module-sage.algebras.affine_nil_temperley_lieb

it should be `/html/en/reference/`

http://doc.sagemath.org/html/en/reference/algebras/sage/algebras/affine_nil_temperley_lieb.html#module-sage.algebras.affine_nil_temperley_lieb

I'll report this upstream.

**Comment by haraldschilly** [comment]
upstream https://trac.sagemath.org/ticket/21044

**Comment by paulmasson** [comment]
I wouldn't block all py-modindex.html files. Many of them have good links.

**Comment by paulmasson** [comment]
This is fixed as of Sage 7.4 and the number of bad links reported by Google is falling daily.
